package com.vinayms.razorpayclone.common.enums;

public enum PaymentEvent {
    PAYMENT_INITIATED,
    AUTHORIZE_ATTEMPT,
    AUTHORIZE_SUCCESS,
    AUTHORIZE_FAIL,
    CAPTURE_REQUEST,
    CAPTURE_SUCCESS,
    CAPTURE_FAIL,
    REFUND_INIT,
    REFUND_COMPLETE,
    REFUND_SUCCESS,
    SETTLE,
    CANCEL,
    CAPTURE_TIMEOUT
}
